community_umbrella/apps/community_web/lib/community_web/router.ex
defmodule CommunityWeb.Router do
  use CommunityWeb, :router

  import CommunityWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug Ueberauth
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {CommunityWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", CommunityWeb do
    pipe_through :browser

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", CommunityWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: CommunityWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", CommunityWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    # post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    # post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", CommunityWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", CommunityWeb do
    pipe_through [:browser]

    scope "/login" do
      get "/:provider", OauthController, :request
      get "/:provider/callback", OauthController, :callback
    end

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end

  scope "/u", CommunityWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/", PageController, :user_home

    scope "/submit" do
      get "", SubmissionController, :new
      get "/:owner/:repo", SubmissionController, :pull
      get "/:owner/:repo/:pull", SubmissionController, :confirm
      post "/", SubmissionController, :create
    end
  end
end

community_umbrella/apps/community_web/lib/community_web/templates/page/index.html.heex
<div class="text-luckypoint text-white flex flex-row h-96 justify-around items-center">
  <div class="flex flex-col items-start justify-center h-full" id="hero-left">
    <h1 class="lg:text-6xl text-3xl">OpenCodeReview.net</h1>
    <h3 class="lg:text-xl text-md">Share your Pull Requests, get peer reviews.</h3>
  </div>
  <div class="flex flex-col justify-center items-center" id="hero-right">
    <%= link(to: Routes.oauth_path(@conn, :request, "github")) do %>
      <%= btn(:primary) do %>
        Continue with Github <i class="fa-brands fa-github"></i>
      <% end %>
    <% end %>
  </div>
</div>

community_umbrella/apps/community_web/lib/community_web/templates/page/user_home.html.heex
<div class="max-w-screen-lg mx-auto">
  <div class="flex flex-col">
    <section class="flex flex-col items-center">
      <div class="w-1/2">
        <%= if @recent_submissions do %>
        <% else %>
          <div class="bg-stone rounded p-4 text-white">
            <p>No submissions yet!</p>
          </div>
        <% end %>
      </div>
      <div class="flex flex-row justify-center pt-4">
        <%= link(to: Routes.submission_path(@conn, :new)) do %>
          <%= btn(:primary, label: "Submit a new RFC") %>
        <% end %>
      </div>
    </section>
  </div>
</div>